[project]
name = "longstrings"
version = "0.1.3"
description = "Find long string comments in Python code"
readme = "README.md"
authors = [
    { name = "Jeff Glass", email = "glass.jeffrey@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []
classifiers = [
  "Development Status :: 5 - Production/Stable",

  # Specify the Python versions you support here.
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",

  "Topic :: Software Development :: Documentation"
]

[project.urls]
Repository = "https://github.com/jeffersglass/longstrings.git"

[project.scripts]
longstrings = "longstrings:entry_point"

[build-system]
requires = ["uv_build>=0.8.5,<0.9.0"]
build-backend = "uv_build"
